# Site settings
title: "Xuesi Chen/陈学思"
description: "personal website for Xuesi Chen."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Xuesi Chen"
resume_title:                   "first-year PhD student at CMU"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "xuesic@andrew.cmu.edu"

resume_header_intro: "<p>I am a first-year PhD student in the Electrical and Computer Engineering Department at Carnegie Mellon University. I am co-advised by Professor Brandon Lucia and Nathan Beckmann. I am broadly interested in computer architecture and currently working on implementing time multiplexing support for energy-minimal programmable architecture.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
# resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/XuesiChen"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/xuesi-chen-65892a13"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
 # resume_medium_url:            "https://medium.com/@jglovier"
#resume_print_social_links:      true

# Design settings
resume_theme:                   default
